apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisicalauth-azure-demo
spec:
  infisicalConnectionRef:
    name: infisicalconnection-demo
    namespace: default
  method: azure
  azure:
    identityIdRef:
      name: azure-credentials
      namespace: default
      key: identityId
