apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisicalauth-ldap-demo
spec:
  infisicalConnectionRef:
    name: infisicalconnection-demo
    namespace: default
  method: ldap
  ldap:
    usernameRef:
      name: ldap-credentials
      namespace: default
      key: username
    passwordRef:
      name: ldap-credentials
      namespace: default
      key: password
    identityIdRef:
      name: ldap-credentials
      namespace: default
      key: identityId
