{{- if .Values.configureBasicKubernetesAuth }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "secrets-operator.fullname" . }}-token-setup-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: token-setup
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "secrets-operator.fullname" . }}-token-setup-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: token-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "secrets-operator.fullname" . }}-token-setup-role
subjects:
- kind: ServiceAccount
  name: {{ include "secrets-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

