{{ if .Values.configureBasicKubernetesAuth }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: infisical-token-reviewer-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: infisical-token-reviewer
{{- end }}