apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: infisicalconnection-demo
spec:
  host: https://app.infisical.com
  tls:
    caCertificate:
      name: secretName
      namespace: default
      key: certificate