//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSIamAuthConfig) DeepCopyInto(out *AWSIamAuthConfig) {
	*out = *in
	out.IdentityIDRef = in.IdentityIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSIamAuthConfig.
func (in *AWSIamAuthConfig) DeepCopy() *AWSIamAuthConfig {
	if in == nil {
		return nil
	}
	out := new(AWSIamAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureAuthConfig) DeepCopyInto(out *AzureAuthConfig) {
	*out = *in
	out.IdentityIDRef = in.IdentityIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureAuthConfig.
func (in *AzureAuthConfig) DeepCopy() *AzureAuthConfig {
	if in == nil {
		return nil
	}
	out := new(AzureAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPIamAuthConfig) DeepCopyInto(out *GCPIamAuthConfig) {
	*out = *in
	out.IdentityIDRef = in.IdentityIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPIamAuthConfig.
func (in *GCPIamAuthConfig) DeepCopy() *GCPIamAuthConfig {
	if in == nil {
		return nil
	}
	out := new(GCPIamAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPIdTokenAuthConfig) DeepCopyInto(out *GCPIdTokenAuthConfig) {
	*out = *in
	out.IdentityIDRef = in.IdentityIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPIdTokenAuthConfig.
func (in *GCPIdTokenAuthConfig) DeepCopy() *GCPIdTokenAuthConfig {
	if in == nil {
		return nil
	}
	out := new(GCPIdTokenAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalAuth) DeepCopyInto(out *InfisicalAuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalAuth.
func (in *InfisicalAuth) DeepCopy() *InfisicalAuth {
	if in == nil {
		return nil
	}
	out := new(InfisicalAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalAuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalAuthList) DeepCopyInto(out *InfisicalAuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalAuthList.
func (in *InfisicalAuthList) DeepCopy() *InfisicalAuthList {
	if in == nil {
		return nil
	}
	out := new(InfisicalAuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalAuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalAuthSpec) DeepCopyInto(out *InfisicalAuthSpec) {
	*out = *in
	out.InfisicalConnectionRef = in.InfisicalConnectionRef
	if in.Universal != nil {
		in, out := &in.Universal, &out.Universal
		*out = new(UniversalAuthConfig)
		**out = **in
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AWSIam != nil {
		in, out := &in.AWSIam, &out.AWSIam
		*out = new(AWSIamAuthConfig)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureAuthConfig)
		**out = **in
	}
	if in.GCPIdToken != nil {
		in, out := &in.GCPIdToken, &out.GCPIdToken
		*out = new(GCPIdTokenAuthConfig)
		**out = **in
	}
	if in.GCPIam != nil {
		in, out := &in.GCPIam, &out.GCPIam
		*out = new(GCPIamAuthConfig)
		**out = **in
	}
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPAuthConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalAuthSpec.
func (in *InfisicalAuthSpec) DeepCopy() *InfisicalAuthSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalAuthStatus) DeepCopyInto(out *InfisicalAuthStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalAuthStatus.
func (in *InfisicalAuthStatus) DeepCopy() *InfisicalAuthStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalAuthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnection) DeepCopyInto(out *InfisicalConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnection.
func (in *InfisicalConnection) DeepCopy() *InfisicalConnection {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionList) DeepCopyInto(out *InfisicalConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfisicalConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionList.
func (in *InfisicalConnectionList) DeepCopy() *InfisicalConnectionList {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfisicalConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionSpec) DeepCopyInto(out *InfisicalConnectionSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionSpec.
func (in *InfisicalConnectionSpec) DeepCopy() *InfisicalConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConnectionStatus) DeepCopyInto(out *InfisicalConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConnectionStatus.
func (in *InfisicalConnectionStatus) DeepCopy() *InfisicalConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(InfisicalConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesAuthConfig) DeepCopyInto(out *KubernetesAuthConfig) {
	*out = *in
	out.IdentityIDRef = in.IdentityIDRef
	out.ServiceAccountRef = in.ServiceAccountRef
	if in.ServiceAccountTokenAudiences != nil {
		in, out := &in.ServiceAccountTokenAudiences, &out.ServiceAccountTokenAudiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesAuthConfig.
func (in *KubernetesAuthConfig) DeepCopy() *KubernetesAuthConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPAuthConfig) DeepCopyInto(out *LDAPAuthConfig) {
	*out = *in
	out.UsernameRef = in.UsernameRef
	out.PasswordRef = in.PasswordRef
	out.IdentityIDRef = in.IdentityIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPAuthConfig.
func (in *LDAPAuthConfig) DeepCopy() *LDAPAuthConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CaCertificate != nil {
		in, out := &in.CaCertificate, &out.CaCertificate
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UniversalAuthConfig) DeepCopyInto(out *UniversalAuthConfig) {
	*out = *in
	out.ClientIdRef = in.ClientIdRef
	out.ClientSecretRef = in.ClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UniversalAuthConfig.
func (in *UniversalAuthConfig) DeepCopy() *UniversalAuthConfig {
	if in == nil {
		return nil
	}
	out := new(UniversalAuthConfig)
	in.DeepCopyInto(out)
	return out
}
