apiVersion: rbac.authorization.k8s.io/v1
{{- if and .Values.scopedNamespace .Values.scopedRBAC }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "secrets-operator.fullname" . }}-infisicalsecret-admin-role
  {{- if and .Values.scopedNamespace .Values.scopedRBAC }}
  namespace: {{ .Values.scopedNamespace | quote }}
  {{- end }}
  labels:
  {{- include "secrets-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicalsecrets
  verbs:
  - '*'
- apiGroups:
  - secrets.infisical.com
  resources:
  - infisicalsecrets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if and .Values.scopedNamespace .Values.scopedRBAC }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "secrets-operator.fullname" . }}-infisicalsecret-admin-rolebinding
  {{- if and .Values.scopedNamespace .Values.scopedRBAC }}
  namespace: {{ .Values.scopedNamespace | quote }}
  {{- end }}
  labels:

  {{- include "secrets-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if and .Values.scopedNamespace .Values.scopedRBAC }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: '{{ include "secrets-operator.fullname" . }}-infisicalsecret-admin-role'
