{{- if and (eq .Values.controllerManager.serviceAccount.create false) (eq .Values.controllerManager.serviceAccount.name "") }}
  {{- fail "if controllerManager.serviceAccount.create = false, a controllerManager.serviceAccount.name must be provided" }}
{{- end }}

{{- if .Values.controllerManager.serviceAccount.create }}

{{- $annotations := deepCopy (.Values.commonAnnotations | default dict) }}
{{- $annotations = mergeOverwrite $annotations (.Values.controllerManager.serviceAccount.annotations | default dict) }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secrets-operator.serviceAccountName" . }}
  labels:
  {{- include "secrets-operator.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}